### PR TITLE
Logout Bugfix

### PR DESCRIPTION
**Pull request by jamesanderson9182**
Also fixed unit tests

### CODE REVIEW

**Comment by acuthbert** [comment]
Hi James - yeah, just checking have you reviewed the diff okay - there's only a few changes, does that fix everything? I ask because I remember recent churn on this module and perhaps the things you're fixing are already fixed, just seemed like very little code to fix all the things you mentioned in the other PR. Might be fine - just asking!

**Comment by jamesanderson9182** [comment]
Yeah, I did. Let me double check and get back to you.

**Comment by jamesanderson9182** [comment]
Hi Bert, Yes I'm confident with those changes. I've tested each commit individually and also the logout function on the current version of master and also with my change. 

I'm using Rhubarb for my dissertation group work project.

James

**Comment by acuthbert** [comment]
Hi James - grab me sometime and we'll take a look at this. I'm not sure how these changes relate to logout?

**Pull request closed without merging**
